name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with: 
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Install Deps
        run: sudo apt update && sudo apt -y install cmake
      - name: Build
        run: mkdir build && cd build && ../cbuild

  build-Docker:

    runs-on: ubuntu-latest
    name: Build Container
    needs: [ build ] # for ignoring bad builds
    if: gitea.event_name == 'push' && (gitea.ref == 'refs/heads/main' || startsWith(gitea.ref, 'refs/tags/'))

    steps:
      - uses: actions/checkout@v4
        with:
          github-server-url: https://gitea.sheep-ghoul.ts.net

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: gitea.sheep-ghoul.ts.net
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build CLI Container
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gitea.sheep-ghoul.ts.net/sarsoo/knowledgecrawler:latest
          file: Dockerfile
          context: .